//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="WinClient.localhost.IImpersonationService")]
    public interface IImpersonationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IImpersonationService/Impersonation" +
            "NotAllowed", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IImpersonationService/Impersonation" +
            "NotAllowedResponse")]
        void ImpersonationNotAllowed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IImpersonationService/Impersonation" +
            "Allowed", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IImpersonationService/Impersonation" +
            "AllowedResponse")]
        void ImpersonationAllowed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IImpersonationService/Impersonation" +
            "Required", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IImpersonationService/Impersonation" +
            "RequiredResponse")]
        void ImpersonationRequired();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IImpersonationServiceChannel : WinClient.localhost.IImpersonationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ImpersonationServiceClient : System.ServiceModel.ClientBase<WinClient.localhost.IImpersonationService>, WinClient.localhost.IImpersonationService
    {
        
        public ImpersonationServiceClient()
        {
        }
        
        public ImpersonationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ImpersonationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ImpersonationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ImpersonationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void ImpersonationNotAllowed()
        {
            base.Channel.ImpersonationNotAllowed();
        }
        
        public void ImpersonationAllowed()
        {
            base.Channel.ImpersonationAllowed();
        }
        
        public void ImpersonationRequired()
        {
            base.Channel.ImpersonationRequired();
        }
    }
}
