//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="WinClient.localhost.ICounterServicePerCall")]
    public interface ICounterServicePerCall
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.thatindigogirl.com/samples/2006/06/ICounterServicePerCall/IncrementCou" +
            "nter")]
        void IncrementCounter();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICounterServicePerCallChannel : WinClient.localhost.ICounterServicePerCall, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CounterServicePerCallClient : System.ServiceModel.ClientBase<WinClient.localhost.ICounterServicePerCall>, WinClient.localhost.ICounterServicePerCall
    {
        
        public CounterServicePerCallClient()
        {
        }
        
        public CounterServicePerCallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CounterServicePerCallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CounterServicePerCallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CounterServicePerCallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void IncrementCounter()
        {
            base.Channel.IncrementCounter();
        }
    }
}
