//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="ProfileClient.localhost.IProfileService")]
    public interface IProfileService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IProfileService/SetCulturePreferenc" +
            "e", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IProfileService/SetCulturePreferenc" +
            "eResponse")]
        void SetCulturePreference(string culture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IProfileService/GetCulturePreferenc" +
            "e", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IProfileService/GetCulturePreferenc" +
            "eResponse")]
        string GetCulturePreference();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IProfileServiceChannel : ProfileClient.localhost.IProfileService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<ProfileClient.localhost.IProfileService>, ProfileClient.localhost.IProfileService
    {
        
        public ProfileServiceClient()
        {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void SetCulturePreference(string culture)
        {
            base.Channel.SetCulturePreference(culture);
        }
        
        public string GetCulturePreference()
        {
            return base.Channel.GetCulturePreference();
        }
    }
}
