//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="WinClient.localhost.ICounterServicePerCall")]
    public interface ICounterServicePerCall
    {
        
        [System.ServiceModel.OperationContractAttribute( Action="http://www.thatindigogirl.com/samples/2006/06/ICounterServicePerCall/IncrementCou" +
            "nter", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICounterServicePerCall/IncrementCou" +
            "nterResponse")]
        int IncrementCounter();
        
        [System.ServiceModel.OperationContractAttribute( Action="http://www.thatindigogirl.com/samples/2006/06/ICounterServicePerCall/ThrowExcepti" +
            "on", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICounterServicePerCall/ThrowExcepti" +
            "onResponse")]
        void ThrowException();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ICounterServicePerCall/ThrowFault", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICounterServicePerCall/ThrowFaultRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.InvalidOperationException), Action="http://www.thatindigogirl.com/samples/2006/06/ICounterServicePerCall/ThrowFaultIn" +
            "validOperationExceptionFault", Name="InvalidOperationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void ThrowFault();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICounterServicePerCallChannel : WinClient.localhost.ICounterServicePerCall, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CounterServicePerCallClient : System.ServiceModel.ClientBase<WinClient.localhost.ICounterServicePerCall>, WinClient.localhost.ICounterServicePerCall
    {
        
        public CounterServicePerCallClient()
        {
        }
        
        public CounterServicePerCallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CounterServicePerCallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CounterServicePerCallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CounterServicePerCallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int IncrementCounter()
        {
            return base.Channel.IncrementCounter();
        }
        
        public void ThrowException()
        {
            base.Channel.ThrowException();
        }
        
        public void ThrowFault()
        {
            base.Channel.ThrowFault();
        }
    }
}
