//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingletonClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="SingletonClient.localhost.ISingletonService")]
    public interface ISingletonService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ISingletonService/IncrementCounter", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ISingletonService/IncrementCounterR" +
            "esponse")]
        void IncrementCounter();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISingletonServiceChannel : SingletonClient.localhost.ISingletonService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SingletonServiceClient : System.ServiceModel.ClientBase<SingletonClient.localhost.ISingletonService>, SingletonClient.localhost.ISingletonService
    {
        
        public SingletonServiceClient()
        {
        }
        
        public SingletonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SingletonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SingletonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SingletonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void IncrementCounter()
        {
            base.Channel.IncrementCounter();
        }
    }
}
