//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="Client.localhost.HelloIndigoContract")]
    public interface HelloIndigoContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/HelloIndigoContract/HelloIndigo", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/HelloIndigoContract/HelloIndigoResp" +
            "onse")]
        string HelloIndigo(string inputString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface HelloIndigoContractChannel : Client.localhost.HelloIndigoContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class HelloIndigoContractClient : System.ServiceModel.ClientBase<Client.localhost.HelloIndigoContract>, Client.localhost.HelloIndigoContract
    {
        
        public HelloIndigoContractClient()
        {
        }
        
        public HelloIndigoContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HelloIndigoContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloIndigoContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloIndigoContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string HelloIndigo(string inputString)
        {
            return base.Channel.HelloIndigo(inputString);
        }
    }
}
