//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="SessionClient.localhost.ISessionService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ISessionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ISessionService/StartSession", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ISessionService/StartSessionRespons" +
            "e")]
        void StartSession();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://www.thatindigogirl.com/samples/2006/06/ISessionService/IncrementCounter", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ISessionService/IncrementCounterRes" +
            "ponse")]
        void IncrementCounter();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://www.thatindigogirl.com/samples/2006/06/ISessionService/GetCounter", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ISessionService/GetCounterResponse")]
        int GetCounter();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://www.thatindigogirl.com/samples/2006/06/ISessionService/GetSessionId", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ISessionService/GetSessionIdRespons" +
            "e")]
        string GetSessionId();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://www.thatindigogirl.com/samples/2006/06/ISessionService/StopSession", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ISessionService/StopSessionResponse" +
            "")]
        void StopSession();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISessionServiceChannel : SessionClient.localhost.ISessionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SessionServiceClient : System.ServiceModel.ClientBase<SessionClient.localhost.ISessionService>, SessionClient.localhost.ISessionService
    {
        
        public SessionServiceClient()
        {
        }
        
        public SessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void StartSession()
        {
            base.Channel.StartSession();
        }
        
        public void IncrementCounter()
        {
            base.Channel.IncrementCounter();
        }
        
        public int GetCounter()
        {
            return base.Channel.GetCounter();
        }
        
        public string GetSessionId()
        {
            return base.Channel.GetSessionId();
        }
        
        public void StopSession()
        {
            base.Channel.StopSession();
        }
    }
}
