//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClient.localhost2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="WinClient.localhost2.ICounterServiceSingle")]
    public interface ICounterServiceSingle
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/ICounterServiceSingle/IncrementCoun" +
            "ter", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/ICounterServiceSingle/IncrementCoun" +
            "terResponse")]
        int IncrementCounter();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICounterServiceSingleChannel : WinClient.localhost2.ICounterServiceSingle, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CounterServiceSingleClient : System.ServiceModel.ClientBase<WinClient.localhost2.ICounterServiceSingle>, WinClient.localhost2.ICounterServiceSingle
    {
        
        public CounterServiceSingleClient()
        {
        }
        
        public CounterServiceSingleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CounterServiceSingleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CounterServiceSingleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CounterServiceSingleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int IncrementCounter()
        {
            return base.Channel.IncrementCounter();
        }
    }
}
